### PR TITLE
release tools

### PR DESCRIPTION
**Pull request by pohly**
This imports the shared csi-release-tools and uses it for Travis CI
and building. The binary and image name are expected to be "iscsiplugin",
but a Dockerfile still needs to be added by someone who knows what needs
to be in it.

/assign @msau42

### CODE REVIEW

**Comment by pohly** [comment]
Travis CI still needs to be activated for this repo. This can only be done by someone in the kubernetes-csi admin group.

**Comment by msau42** [comment]
I enabled travis. We'll see on the next pull if it works. I tried to manually trigger a build, but it was still skipping the image pushing part for some reason

**Comment by pohly** [comment]
Pull request builds don't push images. If they did, which tag should they use?

**Comment by pohly** [comment]
Wait, this repo is the one which doesn't have a Dockerfile, therefore image building is not enabled in the Makefile.

**Pull request merged**
