### PR TITLE
cleanup: use klog instead of debug print

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
cleanup: use klog instead of debug print
there is almost no logging in original debug print, this PR would switch to use klog log print

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by msau42** [comment]
@humblec I thought we were going to move the library here and archive the iscsi-lib?

**Comment by andyzhangx** [comment]
> @humblec I thought we were going to move the library here and archive the iscsi-lib?

@msau42 yes, that's what I was discussing with @humblec two days ago, current iscsi-lib actually has 3 valid go files, it's not necessary to maintain a separate project. Let me work on some code level refactor first, and move the library here and archive the iscsi-lib. I plan to add some tests first to make sure it won't break anything, at least this iscsi driver is already working on Azure now, that's the reason why I would like to spend more time in this project to make it mature.

**Comment by andyzhangx** [comment]
would fix by https://github.com/kubernetes-csi/csi-lib-iscsi/pull/45

**Pull request closed without merging**
