### PR TITLE
master: update release-tools + dependencies

### PR DESCRIPTION
**Pull request by pohly**
Squashed 'release-tools/' changes from 7bc70e5..1748b16

[1748b16](https://github.com/kubernetes-csi/csi-release-tools/commit/1748b16) Merge pull request #136 from pohly/go-1.16
[ec844ea](https://github.com/kubernetes-csi/csi-release-tools/commit/ec844ea) remove travis.yml, Go 1.16
[df76aba](https://github.com/kubernetes-csi/csi-release-tools/commit/df76aba) Merge pull request #134 from andyzhangx/add-build-arg
[e314a56](https://github.com/kubernetes-csi/csi-release-tools/commit/e314a56) add build-arg ARCH for building multi-arch images, e.g. ARG ARCH FROM k8s.gcr.io/build-image/debian-base-${ARCH}:v2.1.3

git-subtree-dir: release-tools
git-subtree-split: 1748b16b488381c34a86ddbee110e9ed523bcb20

```release-note
updated runtime (Go 1.16) and dependencies
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@pohly why do we get the Travis CI failure?

**Comment by pohly** [comment]
> why do we get the Travis CI failure?

Because I removed the travis.yml from csi-release-tools. TravisCI wasn't supposed to be used anymore.

**Comment by pohly** [comment]
I can try removing the (now broken) link. Perhaps that will prevent TravisCI from doing anything with this repo.

**Pull request merged**
