### PR TITLE
iscsi: correct error message format

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

> /kind cleanup

-->
```release-note
NONE
```

### CODE REVIEW

**Comment by humblec** [comment]
The sanity test pass locally, but looks like its timedout in CI.

**Comment by andyzhangx** [comment]
my fault, it would be fixed by: https://github.com/kubernetes-csi/csi-driver-iscsi/pull/85, @humblec could you approve?

**Comment by humblec** [comment]
> my fault, it would be fixed by: #85, @humblec could you approve?

Done.. Hopefully after the merge, this pass.

**Comment by humblec** [comment]
@andyzhangx cool, #85 fixed it. Thanks .. ptal.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
