### PR TITLE
Fix CVEs, add Make targets, update linters

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

This PR covers below:

- [x] update of linters and a couple of linter additions
- [x] makefile target addition
- [x] update of dockerfile to fix CVE
- [x] release-tools update to master   

```release-note
NONE
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@humblec follow this PR to fix the CVE: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/895

**Comment by humblec** [comment]
> @humblec follow this PR to fix the CVE: [kubernetes-sigs/azurefile-csi-driver#895](https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/895)

Oh.. instead of updating `basutils` thought of updating the base image itself and if it goes through..

**Comment by humblec** [comment]
> > @humblec follow this PR to fix the CVE: [kubernetes-sigs/azurefile-csi-driver#895](https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/895)
> 
> Oh.. instead of updating `basutils` thought of updating the base image itself and if it goes through..

@andyzhangx looks like not just base image helps , we need to update the package as well.. trying out.

**Comment by humblec** [comment]
@andyzhangx .. ptal.. this is a mix of few as mentioned in the PR description. :+1:

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by humblec** [comment]
Thanks @andyzhangx for the quick revert!

**Pull request merged**
