### PR TITLE
chore: update pull request template release notes

### PR DESCRIPTION
**Pull request by TerryHowe**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Avoid the need to change 'none' to 'NONE' to follow the directions.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by humblec** [comment]
Thanks @TerryHowe 👍 .

**Comment by TerryHowe** [comment]
The lint test is going to be broken until https://github.com/kubernetes-csi/csi-driver-iscsi/pull/305 merges

**Review by andyzhangx — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by TerryHowe** [comment]
Tests were failing on lint, so hoping that rebase helps

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
